{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.119.666.0 (23.07)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SqlServerInstance\",\"SqlServerDatabase\",\"Culture\",\"Customer\",\"Date\",\"Product\",\"Reseller\",\"Sales\",\"Sales Order\",\"Sales Territory\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "SqlServerInstance",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"POWERBI-SQL\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "e9c56631-f305-47de-9bf2-07193947c24f"
      },
      {
        "name": "SqlServerDatabase",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"AdventureWorksDW2020-DAX-Docs\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "4a7376e0-f9ad-421f-a921-20ff8a97d131"
      },
      {
        "name": "Culture",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "Used to format month names in the Date query.",
        "expression": "\"en-US\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "28a1bb2f-ed54-40b5-a8ab-b1001ec02c3b"
      }
    ],
    "relationships": [
      {
        "name": "c4007daa-09a5-455d-ac3b-d8338a0e4468",
        "fromColumn": "SalesTerritoryKey",
        "fromTable": "Sales",
        "toColumn": "SalesTerritoryKey",
        "toTable": "Sales Territory"
      },
      {
        "name": "fe440ad4-cbfb-4a8c-9b24-4d02f59a009f",
        "fromColumn": "ProductKey",
        "fromTable": "Sales",
        "toColumn": "ProductKey",
        "toTable": "Product"
      },
      {
        "name": "ddc90e12-74d0-451e-87b6-3bc8d773bf07",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "SalesOrderLineKey",
        "fromTable": "Sales",
        "toColumn": "SalesOrderLineKey",
        "toTable": "Sales Order"
      },
      {
        "name": "3921d624-3ba4-40ca-b78d-61fe4ebc7659",
        "fromColumn": "CustomerKey",
        "fromTable": "Sales",
        "toColumn": "CustomerKey",
        "toTable": "Customer"
      },
      {
        "name": "ad03fb2c-8d99-47eb-bdab-0e52920c9d3f",
        "fromColumn": "OrderDateKey",
        "fromTable": "Sales",
        "toColumn": "DateKey",
        "toTable": "Date"
      },
      {
        "name": "a390c257-6a75-4c82-aab5-270f564d26b0",
        "fromColumn": "DueDateKey",
        "fromTable": "Sales",
        "isActive": false,
        "toColumn": "DateKey",
        "toTable": "Date"
      },
      {
        "name": "fcf11ed1-afec-495f-8897-4461f7a9d501",
        "fromColumn": "ShipDateKey",
        "fromTable": "Sales",
        "isActive": false,
        "toColumn": "DateKey",
        "toTable": "Date"
      },
      {
        "name": "f72f8f53-10b5-4d0a-82ea-19e584697a64",
        "fromColumn": "ResellerKey",
        "fromTable": "Sales",
        "toColumn": "ResellerKey",
        "toTable": "Reseller"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "339b1602-774d-44c8-94f2-fdae785d5794",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Country-Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "lineageTag": "532925fc-622f-437c-84ec-70db7030dd6b",
            "sourceColumn": "Country-Region",
            "summarizeBy": "none"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "lineageTag": "1e31427e-086a-4026-87b2-5baa0c4bed01",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c71742f5-ffd0-4027-9cf2-082455495686",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2b3c0f5a-d3cb-47af-a1b4-f48e19a585a3",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "PostalCode",
            "dataType": "string",
            "lineageTag": "fd7ef4dc-af63-498b-ae69-5affebf20bb1",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "State-Province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "c21f743a-50ed-44a8-9ca1-1afb21039689",
            "sourceColumn": "State-Province",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Geography",
            "levels": [
              {
                "name": "Country-Region",
                "column": "Country-Region",
                "lineageTag": "eaee8078-c30f-4ea0-bc0b-964fff8e4acd",
                "ordinal": 0
              },
              {
                "name": "State-Province",
                "column": "State-Province",
                "lineageTag": "c7ad442a-09c1-4807-b92e-ddc03aebc6e5",
                "ordinal": 1
              },
              {
                "name": "City",
                "column": "City",
                "lineageTag": "4576631a-dd00-40bb-8ca9-4626eb6f3ba3",
                "ordinal": 2
              },
              {
                "name": "Postal Code",
                "column": "Postal Code",
                "lineageTag": "27acc8b4-56b8-4cc1-8706-065460de0971",
                "ordinal": 3
              },
              {
                "name": "Customer",
                "column": "Customer",
                "lineageTag": "b85b26cc-68fd-4eec-9146-33f58cc3cb30",
                "ordinal": 4
              }
            ],
            "lineageTag": "713978a8-e48a-48ca-a475-7d1c159feb03"
          }
        ],
        "lineageTag": "acd7fd5e-3e50-4843-8cd5-c8173ce3185d",
        "partitions": [
          {
            "name": "Customer-01f41322-c19c-4b65-a4cb-85a8045da233",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_DimCustomer,{\"CustomerKey\", \"CustomerAlternateKey\", \"FirstName\", \"LastName\", \"DimGeography\"}),",
                "    #\"Expanded DimGeography\" = Table.ExpandRecordColumn(#\"Removed Other Columns\", \"DimGeography\", {\"City\", \"StateProvinceName\", \"EnglishCountryRegionName\", \"PostalCode\"}, {\"City\", \"StateProvinceName\", \"EnglishCountryRegionName\", \"PostalCode\"}),",
                "    #\"Merged Columns\" = Table.CombineColumns(#\"Expanded DimGeography\",{\"FirstName\", \"LastName\"},Combiner.CombineTextByDelimiter(\" \", QuoteStyle.None),\"Customer\"),",
                "    #\"Add NA Row\" = Table.InsertRows(#\"Merged Columns\", 0, {[CustomerKey = -1, CustomerAlternateKey = \"[Not Applicable]\", Customer = \"[Not Applicable]\", City = \"[Not Applicable]\", StateProvinceName =\"[Not Applicable]\", EnglishCountryRegionName =\"[Not Applicable]\", PostalCode =\"[Not Applicable]\"]}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add NA Row\",{{\"CustomerAlternateKey\", \"Customer ID\"}, {\"StateProvinceName\", \"State-Province\"}, {\"EnglishCountryRegionName\", \"Country-Region\"}, {\"PostalCode\", \"Postal Code\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isKey": true,
            "lineageTag": "84ba3894-8e94-4056-b4fe-f953a4f3658b",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "17f50b4c-0b05-4cd7-94c4-558523217c97",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "323c6209-281b-42c2-b2d0-11dd2f02b34f",
            "sourceColumn": "Fiscal Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed7f5c64-6d0c-4754-8653-90c63fcac53b",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "Full Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "lineageTag": "3f8b89ea-ebe9-42a9-b6b0-f1c250985874",
            "sourceColumn": "Full Date",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ef2d223-e428-4e21-b763-1924c9a91040",
            "sortByColumn": "MonthKey",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "MonthKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "923f834e-bebf-4027-b958-65192ab0e99e",
            "sourceColumn": "MonthKey",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "description": "Filters the Sales table using sales order date",
        "hierarchies": [
          {
            "name": "Fiscal",
            "levels": [
              {
                "name": "Year",
                "column": "Fiscal Year",
                "lineageTag": "c9087683-ce0a-4be6-9597-881838a0de29",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Fiscal Quarter",
                "lineageTag": "bbf08657-f8c0-4acf-9c77-1d51b4855e57",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1f9b62a3-b6a9-4928-a5e3-8d8e5da9c747",
                "ordinal": 2
              },
              {
                "name": "Date",
                "column": "Full Date",
                "lineageTag": "f3ed55af-88be-4d24-ad90-ab72c3195317",
                "ordinal": 3
              }
            ],
            "lineageTag": "d1e3a7d3-b23b-4567-b39e-6a41a28934f4"
          }
        ],
        "lineageTag": "d2987997-33f5-451a-be00-88d24390b395",
        "partitions": [
          {
            "name": "Date-6302b3e1-4d31-40e4-b909-ba364d21aa87",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_DimDate,{\"DateKey\", \"FullDateAlternateKey\", \"DayNumberOfMonth\", \"MonthNumberOfYear\", \"CalendarYear\", \"FiscalQuarter\", \"FiscalYear\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"FullDateAlternateKey\", \"Date\"}, {\"FiscalYear\", \"Fiscal Year\"}}),",
                "    #\"Added FY Prefix\" = Table.TransformColumns(#\"Renamed Columns\", {{\"Fiscal Year\", each \"FY\" & Text.From(_, \"en-US\"), type text}}),",
                "    #\"Added Fiscal Quarter\" = Table.AddColumn(#\"Added FY Prefix\", \"Fiscal Quarter\", each [Fiscal Year] & \" Q\" & Number.ToText([FiscalQuarter])),",
                "    #\"Added Month\" = Table.AddColumn(#\"Added Fiscal Quarter\", \"Month\", each (Number.ToText([CalendarYear]) & \" \" & Date.ToText([Date], \"MMM\", Culture)), type text),",
                "    #\"Added Full Date\" = Table.AddColumn(#\"Added Month\", \"Full Date\", each [Month] & \", \" & Text.PadStart(Number.ToText([DayNumberOfMonth]), 2, \"0\")),",
                "    #\"Added MonthKey\" = Table.AddColumn(#\"Added Full Date\", \"MonthKey\", each ([CalendarYear] * 100) + [MonthNumberOfYear]),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Added MonthKey\",{\"DateKey\", \"Date\", \"Fiscal Year\", \"Fiscal Quarter\", \"Month\", \"Full Date\", \"MonthKey\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Other Columns1\",{{\"Fiscal Quarter\", type text}, {\"Month\", type text}, {\"Full Date\", type text}, {\"MonthKey\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f96fde96-9fe1-4ba9-83b0-2caccd094826",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9aba6ca2-16c4-4918-836c-993234b3957a",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "List Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "31741817-34d6-45f0-9ead-b94fd46b2d05",
            "sourceColumn": "List Price",
            "summarizeBy": "none"
          },
          {
            "name": "Model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7de9a04-1a90-4587-916f-696f1edfa195",
            "sourceColumn": "Model",
            "summarizeBy": "none"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "lineageTag": "cb3d39bd-7090-4d6a-bf63-f673feb09a2c",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3619cc03-caa0-44ce-82c8-91a18d405aa3",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "SKU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Stock-keeping unit",
            "lineageTag": "ee0b6018-33e0-4258-8837-f14864be17ac",
            "sourceColumn": "SKU",
            "summarizeBy": "none"
          },
          {
            "name": "Standard Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "b3462209-9084-4f69-ad75-e9accf5e70b8",
            "sourceColumn": "Standard Cost",
            "summarizeBy": "none"
          },
          {
            "name": "Subcategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47041949-2229-4d45-99c2-6e307b2b9f1a",
            "sourceColumn": "Subcategory",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Products",
            "levels": [
              {
                "name": "Category",
                "column": "Category",
                "lineageTag": "3a01dc69-609a-4be5-90f1-c52c411f8b46",
                "ordinal": 0
              },
              {
                "name": "Subcategory",
                "column": "Subcategory",
                "lineageTag": "246b2530-86a5-4df3-8747-b4be98f8db81",
                "ordinal": 1
              },
              {
                "name": "Model",
                "column": "Model",
                "lineageTag": "03592ffc-937c-41a8-95ee-efbb1d0a62db",
                "ordinal": 2
              },
              {
                "name": "Product",
                "column": "Product",
                "lineageTag": "ade39cfd-549c-43e3-ac6c-2cdd11993ef0",
                "ordinal": 3
              }
            ],
            "lineageTag": "a535a373-98a3-422c-8985-c25e57363097"
          }
        ],
        "lineageTag": "ee9d6144-b629-48c7-bddd-92e1581db5b7",
        "measures": [
          {
            "name": "Product Count",
            "expression": [
              "",
              "        COUNTX(",
              "            VALUES('Product'[Product])",
              "            ,COUNT('Product'[Product])",
              "        )"
            ],
            "formatString": "0",
            "lineageTag": "8803d394-9640-402a-9bb7-e72c597b571e"
          }
        ],
        "partitions": [
          {
            "name": "Product-3d5e98b2-a997-4444-96bb-fe1718e2f2b8",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimProduct, each ([FinishedGoodsFlag] = true)),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows\",{\"ProductKey\", \"ProductAlternateKey\", \"EnglishProductName\", \"StandardCost\", \"Color\", \"ListPrice\", \"ModelName\", \"DimProductSubcategory\"}),",
                "    #\"Expanded DimProductSubcategory\" = Table.ExpandRecordColumn(#\"Removed Other Columns\", \"DimProductSubcategory\", {\"EnglishProductSubcategoryName\", \"DimProductCategory\"}, {\"EnglishProductSubcategoryName\", \"DimProductCategory\"}),",
                "    #\"Expanded DimProductCategory\" = Table.ExpandRecordColumn(#\"Expanded DimProductSubcategory\", \"DimProductCategory\", {\"EnglishProductCategoryName\"}, {\"EnglishProductCategoryName\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded DimProductCategory\",{{\"EnglishProductName\", \"Product\"}, {\"StandardCost\", \"Standard Cost\"}, {\"ListPrice\", \"List Price\"}, {\"ModelName\", \"Model\"}, {\"EnglishProductSubcategoryName\", \"Subcategory\"}, {\"EnglishProductCategoryName\", \"Category\"}, {\"ProductAlternateKey\", \"SKU\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Reseller",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Business Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31c18642-2865-4fbc-ac97-117022dcc408",
            "sourceColumn": "Business Type",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "a47470b4-dacd-4f60-affd-80ec55cf50ff",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Country-Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "County",
            "dataType": "string",
            "lineageTag": "65e90cff-14e3-4c14-8327-60997e8cb3f5",
            "sourceColumn": "Country-Region",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "PostalCode",
            "dataType": "string",
            "lineageTag": "2b6b6150-11b6-43bc-9829-981d4e9dbbd5",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Reseller",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "lineageTag": "690a8a57-76be-433e-a558-932216a1f8c2",
            "sourceColumn": "Reseller",
            "summarizeBy": "none"
          },
          {
            "name": "Reseller ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e67be42-6e73-4cc3-b2c6-c88f9418167f",
            "sourceColumn": "Reseller ID",
            "summarizeBy": "none"
          },
          {
            "name": "ResellerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a3de0587-df4e-44f3-a05a-302290f966ae",
            "sourceColumn": "ResellerKey",
            "summarizeBy": "none"
          },
          {
            "name": "State-Province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "76d6b78d-507a-4af0-91e3-49cffa22ef5c",
            "sourceColumn": "State-Province",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Geography",
            "levels": [
              {
                "name": "Country-Region",
                "column": "Country-Region",
                "lineageTag": "96036260-613a-4740-ad37-6e407f7e4127",
                "ordinal": 0
              },
              {
                "name": "State-Province",
                "column": "State-Province",
                "lineageTag": "f0838135-fd3c-49ee-8fdb-4299ab415719",
                "ordinal": 1
              },
              {
                "name": "Postal Code",
                "column": "Postal Code",
                "lineageTag": "3b16f57d-cc79-4036-9d41-28ed199c1a9b",
                "ordinal": 3
              },
              {
                "name": "City",
                "column": "City",
                "lineageTag": "a2704ff7-fba8-49d6-94e8-5e0512ec174f",
                "ordinal": 2
              },
              {
                "name": "Reseller",
                "column": "Reseller",
                "lineageTag": "4b001148-5bfe-4af0-a4d7-9280437f2e67",
                "ordinal": 4
              }
            ],
            "lineageTag": "bae65c16-373c-4447-8561-b7424a36d2a1"
          }
        ],
        "lineageTag": "1134a5a1-91c4-4d64-948d-bef7b0ae7422",
        "partitions": [
          {
            "name": "Reseller-e44d0a71-e144-4c32-b1af-2f758a686c3c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),",
                "    dbo_DimReseller = Source{[Schema=\"dbo\",Item=\"DimReseller\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_DimReseller,{\"ResellerKey\", \"ResellerAlternateKey\", \"BusinessType\", \"ResellerName\", \"DimGeography\"}),",
                "    #\"Expanded DimGeography\" = Table.ExpandRecordColumn(#\"Removed Other Columns\", \"DimGeography\", {\"City\", \"StateProvinceName\", \"EnglishCountryRegionName\", \"PostalCode\"}, {\"City\", \"StateProvinceName\", \"EnglishCountryRegionName\", \"PostalCode\"}),",
                "    #\"Add NA Row\" = Table.InsertRows(#\"Expanded DimGeography\", 0, {[ResellerKey = -1, ResellerAlternateKey = \"[Not Applicable]\", BusinessType = \"[Not Applicable]\", ResellerName = \"[Not Applicable]\", City = \"[Not Applicable]\", StateProvinceName =\"[Not Applicable]\", EnglishCountryRegionName =\"[Not Applicable]\", PostalCode =\"[Not Applicable]\"]}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Add NA Row\",{{\"ResellerAlternateKey\", \"Reseller ID\"}, {\"BusinessType\", \"Business Type\"}, {\"ResellerName\", \"Reseller\"}, {\"StateProvinceName\", \"State-Province\"}, {\"EnglishCountryRegionName\", \"Country-Region\"}, {\"PostalCode\", \"Postal Code\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "@Gross Proft",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "expression": "[Sales Amount] - [Total Product Cost]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1b3edbba-7185-4ddb-812a-66fc2d3fbd8f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6d07ca82-a103-4d49-add9-2eeb69063e96",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "DueDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d34defd6-b5f6-481f-a128-a770479e77d3",
            "sourceColumn": "DueDateKey",
            "summarizeBy": "count"
          },
          {
            "name": "Extended Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "577de386-0e2f-4b43-92f1-e3d59a4ad3d2",
            "sourceColumn": "Extended Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "99cfd3e1-e7a3-438e-8693-4f6c8e08e2c4",
            "sourceColumn": "Order Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "OrderDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ad8fe2b0-5e14-4ef5-a63d-49b57807b83b",
            "sourceColumn": "OrderDateKey",
            "summarizeBy": "none"
          },
          {
            "name": "Product Standard Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "31ad6d28-083a-4af9-95c7-580954ffd7b2",
            "sourceColumn": "Product Standard Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "eecd93ed-19ec-4857-b62c-b10bbdd3efcb",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ResellerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c92da733-f05d-4c90-9670-a3078375ba96",
            "sourceColumn": "ResellerKey",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "02e18607-495b-4a66-9ab8-829acb3e8a70",
            "sourceColumn": "Sales Amount",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderLineKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a02c02a6-cdee-4a88-9b1f-d4e3303b4bcf",
            "sourceColumn": "SalesOrderLineKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cd5e26f2-7479-465d-9576-329e755a56b5",
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "ShipDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b2de657a-8404-4b59-9a9b-dcf4ead314bd",
            "sourceColumn": "ShipDateKey",
            "summarizeBy": "count"
          },
          {
            "name": "Total Product Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "46a421f5-4a6b-49df-adc8-57f468ad2bfd",
            "sourceColumn": "Total Product Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "fee664c3-0319-43bb-97d9-ec7195b98777",
            "sourceColumn": "Unit Price",
            "summarizeBy": "average"
          },
          {
            "name": "Unit Price Discount Pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "81802467-0162-4843-883a-e5b727caf7bd",
            "sourceColumn": "Unit Price Discount Pct",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "545b706e-89bb-432f-84b6-17b216d646d0",
        "measures": [
          {
            "name": "Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "SUM(Sales[Sales Amount])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "94e9c369-446b-459a-9b9c-814907091d1a"
          },
          {
            "name": "Avg Sales Amt",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "AVERAGE(Sales[Sales Amount])",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "aa5d5185-4346-4759-8312-4d2d5917620c"
          },
          {
            "name": "Gross Profit Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "SUM(Sales[@Gross Proft])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "56f8c98d-656b-4bc6-8e6f-2b74682f7efd"
          },
          {
            "name": "Gross Proft",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": "SUM(Sales[Sales Amount]) - SUM(Sales[Total Product Cost])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f9b86419-c26f-4f03-856d-dfb57999a5f9"
          },
          {
            "name": "Top 1 Sales v1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    TOPN(",
              "        1,",
              "        SUMMARIZE(",
              "            Sales,  // Filtered by the relationships, model, and slicer. ",
              "            Sales[Sales Amount]",
              "        )",
              "        ,Sales[Sales Amount]",
              "        ,DESC",
              "        )",
              "    ,[Sales Amount]",
              "    )",
              "        ",
              "    "
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "874f505d-311a-40e6-b925-bdcdea67ca75"
          },
          {
            "name": "Fix 1 - Top 1 Sales Dynamic Row Context",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Top 1 measure fix attempts",
            "expression": [
              "",
              "    // Only works on line items, not in the total aggregate line.",
              "    IF (",
              "        HASONEVALUE('Product'[Category]),",
              "        // Line item",
              "        SUMX(",
              "            TOPN(",
              "                1,",
              "                SUMMARIZE(",
              "                    Sales,",
              "                    Sales[Sales Amount]",
              "                )",
              "                ,Sales[Sales Amount]",
              "                ,DESC",
              "                )",
              "            ,[Sales Amount]",
              "            )",
              "        ,",
              "        // Total",
              "        // Need to reproduce the query context.",
              "        // Sum total across ALL product categories for this resller in the time period.",
              "        // The filter context is handled by the relationships and the slicer.",
              "       ",
              "        CALCULATE(",
              "            SUM(Sales[Sales Amount])",
              "        )",
              "",
              "        // ... what about the group by columns and the aggregate filter value?  Maybe I should summarize the query.",
              "    )",
              "",
              "        ",
              "    "
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "4a12985d-646d-4687-9af8-39245f79069b"
          },
          {
            "name": "Fix 2 - Top 1 Sales Dynamic Row Context",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Top 1 measure fix attempts",
            "expression": [
              "",
              "    VAR _HASONEVALUE = HASONEVALUE('Product'[Category])",
              "",
              "    VAR _TOTAL_SALES = ",
              "        IF (",
              "            _HASONEVALUE = TRUE(),",
              "            SUMX(",
              "                TOPN(",
              "                    1,",
              "                    // This could be rewritten to use SUMMARIZECOLUMNS. See below for example. Not using ADDCOLUMNS/SUMMARIZE pattern.",
              "                    // SUMMARIZE keeps both a row context and a filter context active in the expression where you specify the aggregation.",
              "                    // This function relies on the incoming row context. e.g. Reseller, Product Category.",
              "                    // The filter context is the Order Date range.",
              "                    SUMMARIZE(",
              "                        Sales,",
              "                        Sales[Sales Amount]",
              "                    )",
              "                    ,Sales[Sales Amount]",
              "                    ,DESC",
              "                    )",
              "                ,[Sales Amount]",
              "                )",
              "        ,   ",
              "            // Fetch all the sales rows per reseller, product category, per time period",
              "            // ** Reminder:  SUMMARIZECOLUMNS, is just a replacement of SUMMARIZE",
              "            // Replace ADDCOLUMNS/SUMMARIZE and SUMMARIZE with SUMMARIZECOLUMNS, because the resulting query plan is more efficient.",
              "            // You do NOT have a row context to the columns you are grouping, you must use VALUES to retrieve such a value from the filter context.",
              "            // https://www.sqlbi.com/articles/introducing-summarizecolumns/",
              "            ",
              "            // I do not want blank values for resellers and product category with no sales.  Sales Amount is used in the aggregate expression. Added filter table.",
              "            VAR _SALES_ITER =",
              "                SUMMARIZECOLUMNS(",
              "                    Reseller[Reseller],     // Filter column",
              "                    Product[Category],      // Filter column",
              "                    'Date'[Fiscal Year],    // Filter column",
              "                    'Date'[Fiscal Quarter], // Filter column",
              "                    Sales,              // Filter table.  Need filter context to reduce Sales rows.",
              "                    \"@Total Sales\",SUMX(Sales, Sales[Sales Amount])   // Aggregate calculation              ",
              "                    )",
              "",
              "            // Works in DAX Studio, but not in a measure. ",
              "            // SUMMARIZECOLUMNS cannot be used in a measure.",
              "            // SUMMARIZECOLUMNS cannot be used if the filter context contains a row context or a filter context generated by context transition or an arbitrarily ",
              "            // shaped set. This limitation makes it unusable in any measure. It is a function intended solely for queries and calculated tables.",
              "            VAR _TotalSales = ",
              "                SUMX(",
              "                    TOPN(",
              "                        1,",
              "                        _SALES_ITER",
              "                        ,[@Total Sales]",
              "                        ,DESC",
              "                        )",
              "                    ,[@Total Sales]",
              "                    )",
              "            RETURN _TotalSales",
              "        )",
              "",
              "    RETURN _TOTAL_SALES"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c9c6a045-e47d-4326-b741-282b67c46d46"
          },
          {
            "name": "Fix 3 - Top 1 Sales Dynamic Row Context",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Top 1 measure fix attempts",
            "expression": [
              "",
              "// Only works on line items, not in the total aggregate line.",
              "    IF (",
              "        HASONEVALUE('Product'[Category]),",
              "        SUMX(",
              "            TOPN(",
              "                1,",
              "                SUMMARIZE(",
              "                    Sales,",
              "                    Sales[Sales Amount]",
              "                )",
              "                ,Sales[Sales Amount]",
              "                ,DESC",
              "                )",
              "            ,[Sales Amount]",
              "            )",
              "            ",
              "        ,",
              "        //Step 1. Generate an iterator that for Reseller, Category, filter by Sales Period.",
              "        //Step 2. Sum sales per row context.",
              "        //VAR _SALES_ITERATOR = SUMMARIZE(Sales, Reseller[Reseller], Product[Category], 'Date'[Fiscal Year])",
              "        VAR _SALES_ITERATOR = SUMMARIZE(Sales, Reseller[Reseller],Product[Category])",
              "",
              "        VAR _SALES_PER_RESELLER =",
              "            GENERATE(",
              "                _SALES_ITERATOR",
              "                ,",
              "                    SELECTCOLUMNS(",
              "                        TOPN(",
              "                            1",
              "                            // Context transition for each row in _SALES_ITERATOR",
              "                            ,CALCULATETABLE(Sales)",
              "                            // Sum the sales amount per Reseller[Reseller], Product[Category]",
              "                            ,Sales[Sales Amount] ",
              "                            ,DESC",
              "                        )",
              "                        ,\"TOP 1 Sales\", [Sales Amount]",
              "                    )",
              "                )",
              "",
              "        VAR _RESULT = SUMX(_SALES_PER_RESELLER, [TOP 1 Sales])",
              "        RETURN _RESULT",
              " ",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b7098ef0-5fc7-4cf7-a963-79a60d38786f"
          },
          {
            "name": "Debug - Sales Filter Context Count",
            "displayFolder": "Debug Helpers",
            "expression": [
              "",
              "COUNTROWS(",
              "    Sales",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "628449da-59a9-469a-8caa-eb752b725b00"
          },
          {
            "name": "Debug - DumpFilters",
            "displayFolder": "Debug Helpers",
            "expression": [
              "",
              "VAR MaxFilters = 3",
              "RETURN",
              "IF ( ",
              "    ISFILTERED ( _Measures[Column] ), ",
              "    VAR ___f = FILTERS ( _Measures[Column] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, _Measures[Column] )",
              "    VAR ___d = CONCATENATEX ( ___t, _Measures[Column], \", \" )",
              "    VAR ___x = \"_Measures[Column] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customer[City] ), ",
              "    VAR ___f = FILTERS ( Customer[City] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customer[City] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customer[City], \", \" )",
              "    VAR ___x = \"Customer[City] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customer[Country-Region] ), ",
              "    VAR ___f = FILTERS ( Customer[Country-Region] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customer[Country-Region] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customer[Country-Region], \", \" )",
              "    VAR ___x = \"Customer[Country-Region] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customer[Customer] ), ",
              "    VAR ___f = FILTERS ( Customer[Customer] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customer[Customer] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customer[Customer], \", \" )",
              "    VAR ___x = \"Customer[Customer] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customer[Customer ID] ), ",
              "    VAR ___f = FILTERS ( Customer[Customer ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customer[Customer ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customer[Customer ID], \", \" )",
              "    VAR ___x = \"Customer[Customer ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customer[CustomerKey] ), ",
              "    VAR ___f = FILTERS ( Customer[CustomerKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customer[CustomerKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customer[CustomerKey], \", \" )",
              "    VAR ___x = \"Customer[CustomerKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customer[Postal Code] ), ",
              "    VAR ___f = FILTERS ( Customer[Postal Code] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customer[Postal Code] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customer[Postal Code], \", \" )",
              "    VAR ___x = \"Customer[Postal Code] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Customer[State-Province] ), ",
              "    VAR ___f = FILTERS ( Customer[State-Province] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Customer[State-Province] )",
              "    VAR ___d = CONCATENATEX ( ___t, Customer[State-Province], \", \" )",
              "    VAR ___x = \"Customer[State-Province] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Date] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Date], \", \" )",
              "    VAR ___x = \"'Date'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[DateKey] ), ",
              "    VAR ___f = FILTERS ( 'Date'[DateKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[DateKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[DateKey], \", \" )",
              "    VAR ___x = \"'Date'[DateKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Fiscal Quarter] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Fiscal Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Fiscal Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Fiscal Quarter], \", \" )",
              "    VAR ___x = \"'Date'[Fiscal Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Fiscal Year] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Fiscal Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Fiscal Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Fiscal Year], \", \" )",
              "    VAR ___x = \"'Date'[Fiscal Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Full Date] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Full Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Full Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Full Date], \", \" )",
              "    VAR ___x = \"'Date'[Full Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Month] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Month], \", \" )",
              "    VAR ___x = \"'Date'[Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[MonthKey] ), ",
              "    VAR ___f = FILTERS ( 'Date'[MonthKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[MonthKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[MonthKey], \", \" )",
              "    VAR ___x = \"'Date'[MonthKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Product'[Category] ), ",
              "    VAR ___f = FILTERS ( 'Product'[Category] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Product'[Category] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Product'[Category], \", \" )",
              "    VAR ___x = \"'Product'[Category] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Product'[Color] ), ",
              "    VAR ___f = FILTERS ( 'Product'[Color] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Product'[Color] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Product'[Color], \", \" )",
              "    VAR ___x = \"'Product'[Color] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Product'[List Price] ), ",
              "    VAR ___f = FILTERS ( 'Product'[List Price] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Product'[List Price] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Product'[List Price], \", \" )",
              "    VAR ___x = \"'Product'[List Price] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Product'[Model] ), ",
              "    VAR ___f = FILTERS ( 'Product'[Model] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Product'[Model] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Product'[Model], \", \" )",
              "    VAR ___x = \"'Product'[Model] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Product'[Product] ), ",
              "    VAR ___f = FILTERS ( 'Product'[Product] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Product'[Product] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Product'[Product], \", \" )",
              "    VAR ___x = \"'Product'[Product] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Product'[ProductKey] ), ",
              "    VAR ___f = FILTERS ( 'Product'[ProductKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Product'[ProductKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Product'[ProductKey], \", \" )",
              "    VAR ___x = \"'Product'[ProductKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Product'[SKU] ), ",
              "    VAR ___f = FILTERS ( 'Product'[SKU] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Product'[SKU] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Product'[SKU], \", \" )",
              "    VAR ___x = \"'Product'[SKU] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Product'[Standard Cost] ), ",
              "    VAR ___f = FILTERS ( 'Product'[Standard Cost] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Product'[Standard Cost] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Product'[Standard Cost], \", \" )",
              "    VAR ___x = \"'Product'[Standard Cost] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Product'[Subcategory] ), ",
              "    VAR ___f = FILTERS ( 'Product'[Subcategory] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Product'[Subcategory] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Product'[Subcategory], \", \" )",
              "    VAR ___x = \"'Product'[Subcategory] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Reseller[Business Type] ), ",
              "    VAR ___f = FILTERS ( Reseller[Business Type] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Reseller[Business Type] )",
              "    VAR ___d = CONCATENATEX ( ___t, Reseller[Business Type], \", \" )",
              "    VAR ___x = \"Reseller[Business Type] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Reseller[City] ), ",
              "    VAR ___f = FILTERS ( Reseller[City] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Reseller[City] )",
              "    VAR ___d = CONCATENATEX ( ___t, Reseller[City], \", \" )",
              "    VAR ___x = \"Reseller[City] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Reseller[Country-Region] ), ",
              "    VAR ___f = FILTERS ( Reseller[Country-Region] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Reseller[Country-Region] )",
              "    VAR ___d = CONCATENATEX ( ___t, Reseller[Country-Region], \", \" )",
              "    VAR ___x = \"Reseller[Country-Region] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Reseller[Postal Code] ), ",
              "    VAR ___f = FILTERS ( Reseller[Postal Code] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Reseller[Postal Code] )",
              "    VAR ___d = CONCATENATEX ( ___t, Reseller[Postal Code], \", \" )",
              "    VAR ___x = \"Reseller[Postal Code] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Reseller[Reseller] ), ",
              "    VAR ___f = FILTERS ( Reseller[Reseller] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Reseller[Reseller] )",
              "    VAR ___d = CONCATENATEX ( ___t, Reseller[Reseller], \", \" )",
              "    VAR ___x = \"Reseller[Reseller] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Reseller[Reseller ID] ), ",
              "    VAR ___f = FILTERS ( Reseller[Reseller ID] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Reseller[Reseller ID] )",
              "    VAR ___d = CONCATENATEX ( ___t, Reseller[Reseller ID], \", \" )",
              "    VAR ___x = \"Reseller[Reseller ID] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Reseller[ResellerKey] ), ",
              "    VAR ___f = FILTERS ( Reseller[ResellerKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Reseller[ResellerKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, Reseller[ResellerKey], \", \" )",
              "    VAR ___x = \"Reseller[ResellerKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Reseller[State-Province] ), ",
              "    VAR ___f = FILTERS ( Reseller[State-Province] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Reseller[State-Province] )",
              "    VAR ___d = CONCATENATEX ( ___t, Reseller[State-Province], \", \" )",
              "    VAR ___x = \"Reseller[State-Province] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[@Gross Proft] ), ",
              "    VAR ___f = FILTERS ( Sales[@Gross Proft] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[@Gross Proft] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[@Gross Proft], \", \" )",
              "    VAR ___x = \"Sales[@Gross Proft] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[CustomerKey] ), ",
              "    VAR ___f = FILTERS ( Sales[CustomerKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[CustomerKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[CustomerKey], \", \" )",
              "    VAR ___x = \"Sales[CustomerKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[DueDateKey] ), ",
              "    VAR ___f = FILTERS ( Sales[DueDateKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[DueDateKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[DueDateKey], \", \" )",
              "    VAR ___x = \"Sales[DueDateKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[Extended Amount] ), ",
              "    VAR ___f = FILTERS ( Sales[Extended Amount] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[Extended Amount] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[Extended Amount], \", \" )",
              "    VAR ___x = \"Sales[Extended Amount] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[Order Quantity] ), ",
              "    VAR ___f = FILTERS ( Sales[Order Quantity] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[Order Quantity] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[Order Quantity], \", \" )",
              "    VAR ___x = \"Sales[Order Quantity] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[OrderDateKey] ), ",
              "    VAR ___f = FILTERS ( Sales[OrderDateKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[OrderDateKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[OrderDateKey], \", \" )",
              "    VAR ___x = \"Sales[OrderDateKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[Product Standard Cost] ), ",
              "    VAR ___f = FILTERS ( Sales[Product Standard Cost] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[Product Standard Cost] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[Product Standard Cost], \", \" )",
              "    VAR ___x = \"Sales[Product Standard Cost] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[ProductKey] ), ",
              "    VAR ___f = FILTERS ( Sales[ProductKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[ProductKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[ProductKey], \", \" )",
              "    VAR ___x = \"Sales[ProductKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[ResellerKey] ), ",
              "    VAR ___f = FILTERS ( Sales[ResellerKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[ResellerKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[ResellerKey], \", \" )",
              "    VAR ___x = \"Sales[ResellerKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[Sales Amount] ), ",
              "    VAR ___f = FILTERS ( Sales[Sales Amount] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[Sales Amount] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[Sales Amount], \", \" )",
              "    VAR ___x = \"Sales[Sales Amount] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[SalesOrderLineKey] ), ",
              "    VAR ___f = FILTERS ( Sales[SalesOrderLineKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[SalesOrderLineKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[SalesOrderLineKey], \", \" )",
              "    VAR ___x = \"Sales[SalesOrderLineKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[SalesTerritoryKey] ), ",
              "    VAR ___f = FILTERS ( Sales[SalesTerritoryKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[SalesTerritoryKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[SalesTerritoryKey], \", \" )",
              "    VAR ___x = \"Sales[SalesTerritoryKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[ShipDateKey] ), ",
              "    VAR ___f = FILTERS ( Sales[ShipDateKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[ShipDateKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[ShipDateKey], \", \" )",
              "    VAR ___x = \"Sales[ShipDateKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[Total Product Cost] ), ",
              "    VAR ___f = FILTERS ( Sales[Total Product Cost] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[Total Product Cost] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[Total Product Cost], \", \" )",
              "    VAR ___x = \"Sales[Total Product Cost] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[Unit Price] ), ",
              "    VAR ___f = FILTERS ( Sales[Unit Price] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[Unit Price] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[Unit Price], \", \" )",
              "    VAR ___x = \"Sales[Unit Price] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Sales[Unit Price Discount Pct] ), ",
              "    VAR ___f = FILTERS ( Sales[Unit Price Discount Pct] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Sales[Unit Price Discount Pct] )",
              "    VAR ___d = CONCATENATEX ( ___t, Sales[Unit Price Discount Pct], \", \" )",
              "    VAR ___x = \"Sales[Unit Price Discount Pct] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Order'[Channel] ), ",
              "    VAR ___f = FILTERS ( 'Sales Order'[Channel] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Order'[Channel] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Order'[Channel], \", \" )",
              "    VAR ___x = \"'Sales Order'[Channel] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Order'[Sales Order] ), ",
              "    VAR ___f = FILTERS ( 'Sales Order'[Sales Order] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Order'[Sales Order] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Order'[Sales Order], \", \" )",
              "    VAR ___x = \"'Sales Order'[Sales Order] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Order'[Sales Order Line] ), ",
              "    VAR ___f = FILTERS ( 'Sales Order'[Sales Order Line] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Order'[Sales Order Line] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Order'[Sales Order Line], \", \" )",
              "    VAR ___x = \"'Sales Order'[Sales Order Line] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Order'[SalesOrderLineKey] ), ",
              "    VAR ___f = FILTERS ( 'Sales Order'[SalesOrderLineKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Order'[SalesOrderLineKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Order'[SalesOrderLineKey], \", \" )",
              "    VAR ___x = \"'Sales Order'[SalesOrderLineKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Territory'[Country] ), ",
              "    VAR ___f = FILTERS ( 'Sales Territory'[Country] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Territory'[Country] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Territory'[Country], \", \" )",
              "    VAR ___x = \"'Sales Territory'[Country] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Territory'[Group] ), ",
              "    VAR ___f = FILTERS ( 'Sales Territory'[Group] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Territory'[Group] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Territory'[Group], \", \" )",
              "    VAR ___x = \"'Sales Territory'[Group] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Territory'[Region] ), ",
              "    VAR ___f = FILTERS ( 'Sales Territory'[Region] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Territory'[Region] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Territory'[Region], \", \" )",
              "    VAR ___x = \"'Sales Territory'[Region] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Territory'[SalesTerritoryKey] ), ",
              "    VAR ___f = FILTERS ( 'Sales Territory'[SalesTerritoryKey] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Territory'[SalesTerritoryKey] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Territory'[SalesTerritoryKey], \", \" )",
              "    VAR ___x = \"'Sales Territory'[SalesTerritoryKey] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")"
            ],
            "lineageTag": "1a19b64e-3082-4762-99e1-29d156d95c6f"
          },
          {
            "name": "Debug - Matrix Scope",
            "displayFolder": "Debug Helpers",
            "expression": [
              "",
              "    // What is the finest group by granularity",
              "    SWITCH (",
              "        TRUE()",
              "        ,ISINSCOPE('Date'[Fiscal Quarter]), \"'Date'[Fiscal Quarter]\"",
              "        ,ISINSCOPE('Product'[Subcategory]), \"'Product'[Subcategory]\"",
              "        ,ISINSCOPE('Product'[Category]), \"'Product'[Category]\"",
              "        ,ISINSCOPE('Reseller'[Reseller]), \"'Reseller'[Reseller]\"",
              "        ,\"Other\"",
              "    )"
            ],
            "lineageTag": "1cb57f89-e3b9-482a-8928-adaa5ed5d70f"
          },
          {
            "name": "TOP 1 - Do not show resller sub total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "// Do not show the resller name in the row sub total",
              "    IF (",
              "        HASONEVALUE('Product'[Category]),",
              "        SUMX(",
              "            TOPN(",
              "                1,",
              "                SUMMARIZE(",
              "                    Sales,",
              "                    Sales[Sales Amount]",
              "                )",
              "                ,Sales[Sales Amount]",
              "                ,DESC",
              "                )",
              "            ,[Sales Amount]",
              "            )",
              "            ",
              "        ,",
              "        //Step 1. Generate an iterator that for Reseller, Category, filter by Sales Period.",
              "        //Step 2. Sum sales per row context.",
              "        //VAR _SALES_CATEGORY_ITERATOR = SUMMARIZE(Sales, Reseller[Reseller], Product[Category], 'Date'[Fiscal Year], 'Date'[Fiscal Quarter])",
              "        VAR _SALES_CATEGORY_ITERATOR = SUMMARIZE(Sales, Reseller[Reseller])",
              "",
              "        VAR _SALES_PER_RESELLER =",
              "            GENERATE(",
              "                _SALES_CATEGORY_ITERATOR",
              "                ,",
              "                    SELECTCOLUMNS(",
              "                        TOPN(",
              "                            1",
              "                            // Context transition for each row in _SALES_CATEGORY_ITERATOR",
              "                            ,CALCULATETABLE(Sales)",
              "                            // Sum the sales amount per Reseller[Reseller], Product[Category]",
              "                            ,Sales[Sales Amount] ",
              "                            ,DESC",
              "                            ,Sales[OrderDateKey]",
              "                            ,DESC",
              "                        )",
              "                        ,\"TOP 1 Sales\", [Sales Amount]",
              "                    )",
              "                )",
              "                ",
              "        VAR _RESULT = SUMX(_SALES_PER_RESELLER, [TOP 1 Sales])",
              "    ",
              "        //Turn off sub total value.",
              "        RETURN IF ([Debug - Matrix Scope] = \"'Reseller'[Reseller]\", BLANK(), _RESULT)",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b2c65741-c279-4238-874a-63a2b5111ed6"
          },
          {
            "name": "Sales Row Count",
            "expression": "COUNTROWS(Sales)",
            "formatString": "0",
            "lineageTag": "6667f7f4-3800-4de4-a19f-e83b8729bc8d"
          },
          {
            "name": "Fix 4 - Top 1 Sales Dynamic Row Context",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Top 1 measure fix attempts",
            "expression": [
              "",
              "// Only works on line items, not in the total aggregate line.",
              "    IF (",
              "        HASONEVALUE('Product'[Category]),",
              "        SUMX(",
              "            TOPN(",
              "                1,",
              "                SUMMARIZE(",
              "                    Sales,",
              "                    Sales[Sales Amount]",
              "                )",
              "                ,Sales[Sales Amount]",
              "                ,DESC",
              "                )",
              "            ,[Sales Amount]",
              "            )",
              "            ",
              "        ,",
              "        //Step 1. Generate an iterator that for Reseller, Category, filter by Sales Period.",
              "        //Step 2. Sum sales per row context.",
              "        //VAR _SALES_ITERATOR = SUMMARIZE(Sales, Reseller[Reseller], Product[Category], 'Date'[Fiscal Year])",
              "        VAR _SALES_ITERATOR = SUMMARIZE(Sales, Reseller[Reseller],Product[Category])",
              "",
              "        VAR _SALES_PER_RESELLER =",
              "            GENERATE(",
              "                _SALES_ITERATOR",
              "                ,",
              "                    SELECTCOLUMNS(",
              "                        TOPN(",
              "                            1",
              "                            // Context transition for each row in _SALES_ITERATOR",
              "                            ,CALCULATETABLE(",
              "                                ADDCOLUMNS(",
              "                                    Sales",
              "                                    ,\"@Tie Breaker\", RAND() * 1000",
              "                                )",
              "                            )",
              "                            // Sum the sales amount per Reseller[Reseller], Product[Category]",
              "                            ,Sales[Sales Amount] ",
              "                            ,DESC",
              "                            ,[@Tie Breaker]",
              "                            ,ASC",
              "                        )",
              "                        ,\"TOP 1 Sales\", [Sales Amount]",
              "                    )",
              "                )",
              "",
              "        VAR _RESULT = SUMX(_SALES_PER_RESELLER, [TOP 1 Sales])",
              "        RETURN _RESULT",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "98b3eb18-0761-4127-9bda-fbd11cbcbbda"
          }
        ],
        "partitions": [
          {
            "name": "Sales-1c496a38-f0f4-4d25-b987-657177c38553",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),",
                "    dbo_vFactSales = Source{[Schema=\"dbo\",Item=\"vFactSales\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_vFactSales,{\"SalesOrderLineKey\", \"ResellerKey\", \"CustomerKey\", \"ProductKey\", \"OrderDateKey\", \"DueDateKey\", \"ShipDateKey\", \"SalesTerritoryKey\", \"OrderQuantity\", \"UnitPrice\", \"ExtendedAmount\", \"UnitPriceDiscountPct\", \"ProductStandardCost\", \"TotalProductCost\", \"SalesAmount\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Other Columns\",{{\"OrderQuantity\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"ExtendedAmount\", \"Extended Amount\"}, {\"OrderQuantity\", \"Order Quantity\"}, {\"ProductStandardCost\", \"Product Standard Cost\"}, {\"SalesAmount\", \"Sales Amount\"}, {\"TotalProductCost\", \"Total Product Cost\"}, {\"UnitPrice\", \"Unit Price\"}, {\"UnitPriceDiscountPct\", \"Unit Price Discount Pct\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales Order",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9169fa89-85ad-4562-aeeb-3f9e887af71d",
            "sourceColumn": "Channel",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfccceb1-86b8-4d28-ba47-1e3a8273a820",
            "sourceColumn": "Sales Order",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Line",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "lineageTag": "c24888cb-d331-435f-af83-73a41371a040",
            "sortByColumn": "SalesOrderLineKey",
            "sourceColumn": "Sales Order Line",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderLineKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "61ec0d23-f36e-4993-a3f0-9636dea87c58",
            "sourceColumn": "SalesOrderLineKey",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Sales Orders",
            "levels": [
              {
                "name": "Sales Order",
                "column": "Sales Order",
                "lineageTag": "341cac34-325b-48f1-ade6-2d6817527b31",
                "ordinal": 0
              },
              {
                "name": "Sales Order Line",
                "column": "Sales Order Line",
                "lineageTag": "e54007a8-9219-4f30-ace3-b848493f5db5",
                "ordinal": 1
              }
            ],
            "lineageTag": "e3c0fd2a-6f90-4bb7-8210-7e51e70e5516"
          }
        ],
        "lineageTag": "1afaaa03-c816-4724-968c-1ae833839168",
        "partitions": [
          {
            "name": "Sales Order-3ce1b467-3e1b-4732-b605-3e94fee75991",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),",
                "    dbo_vFactSales = Source{[Schema=\"dbo\",Item=\"vFactSales\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_vFactSales,{\"Channel\", \"SalesOrderLineKey\", \"SalesOrderNumber\", \"SalesOrderLineNumber\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"SalesOrderNumber\", \"Sales Order\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"Sales Order Line\", each [Sales Order] & \" - \" & Text.PadStart(Number.ToText([SalesOrderLineNumber]), 2, \"0\")),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Sales Order Line\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"SalesOrderLineNumber\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales Territory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95080c3f-d66d-4ed2-9b49-9a76d9c1c204",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2988d6f7-3945-4f43-8101-730a9d43becc",
            "sourceColumn": "Group",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "lineageTag": "8ce32283-8672-4e23-aa4b-ec0d3492a29c",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d994ad6f-992d-4e94-b900-cab57ede98d8",
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Sales Territories",
            "levels": [
              {
                "name": "Group",
                "column": "Group",
                "lineageTag": "bd429889-68e6-4bea-857b-340d0de193d2",
                "ordinal": 0
              },
              {
                "name": "Region",
                "column": "Region",
                "lineageTag": "bc98ed08-ade6-4cd2-9862-2e8de3adb4b2",
                "ordinal": 2
              },
              {
                "name": "Country",
                "column": "Country",
                "lineageTag": "80e00ce4-dd09-46f3-a69d-3b39ee813694",
                "ordinal": 1
              }
            ],
            "lineageTag": "cfee4658-015c-4e54-8e7c-ea483f99d9d7"
          }
        ],
        "lineageTag": "20798880-028b-4dde-9128-383ad2d8c92d",
        "partitions": [
          {
            "name": "Sales Territory-86e24776-e692-45a5-9e92-91af2c36c1a6",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),",
                "    dbo_DimSalesTerritory = Source{[Schema=\"dbo\",Item=\"DimSalesTerritory\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_DimSalesTerritory,{\"SalesTerritoryKey\", \"SalesTerritoryRegion\", \"SalesTerritoryCountry\", \"SalesTerritoryGroup\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"SalesTerritoryRegion\", \"Region\"}, {\"SalesTerritoryCountry\", \"Country\"}, {\"SalesTerritoryGroup\", \"Group\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e0d53094cd304483896cd2bc4fc249a5"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d48f25d5-ce19-4b66-abd6-ebfba32aa452",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "74430fcf-854f-4bed-a590-7c758a8730c2",
        "measures": [
          {
            "name": "Use Relationship Example",
            "displayFolder": "Sample Functions",
            "expression": [
              "",
              "",
              "// USERELATIONSHIPS to make a relationship active in the DAX context",
              "",
              "EVALUATE {CALCULATE(SUM(Sales[Sales Amount]),USERELATIONSHIP(Sales[ShipDateKey], 'Date'[DateKey]),'Date'[Fiscal Year] = \"FY2020\")}",
              "",
              "",
              ""
            ],
            "lineageTag": "557b054c-cce9-451c-9161-5f164a958b66"
          },
          {
            "name": "Use Cross Filter Example",
            "displayFolder": "Sample Functions",
            "expression": [
              "",
              "",
              "// When was the last time we shipped a red product?CROSSFILTER to filter the from the fact to the dimension.",
              "",
              "EVALUATE{CALCULATE(MAX ( 'Date'[DateKey] ),CROSSFILTER ( Sales[ShipDateKey], 'Date'[DateKey], BOTH ),'Product'[Color] = \"Red\")}",
              ""
            ],
            "lineageTag": "05c0d805-c716-40cb-999e-3f8468570f55"
          },
          {
            "name": "Total Sales 2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "My functional area 1",
            "expression": [
              "",
              "    // Modifying the filter context using calculate.",
              "    CALCULATE(",
              "        SUM(Sales[Sales Amount])",
              "        ,ALL(Sales)  // Ignoring any fitlers on Sales. ",
              "    )",
              "    ",
              "    //SUMX(ALL('Sales'), Sales[Sales Amount])",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d9f5a79a-e2d2-4006-b6fe-fe775dec66e4"
          },
          {
            "name": "Total Sales 1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "My functional area 1",
            "expression": [
              "SUM(Sales[Sales Amount])",
              "",
              "// My new comments"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6bc2cb4f-7b53-496c-8862-6dbadfdb05f7"
          }
        ],
        "partitions": [
          {
            "name": "_Measures-c6c79fc1-2c37-412c-9e9e-577743b78cc4",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}